### PR TITLE
Add extra buttons on right click

### PR DESCRIPTION
**Pull request by bfred-it**
d

What do you think?

If you approve, don't merge this, but I suggest selecting the Rebase option, so we can avoid unnecessary merge commits :)

### CODE REVIEW

**Comment by bfred-it** [comment]
In the gif you can't see it correctly and I made a change so you only need to right click once to show the buttons for every extension.

# Normal view (same as before)

normal state

# After one right click

extended state

This will allow the extension to look lightweight but still show all the options after one click.

**Comment by bfred-it** [comment]
This gif is clearer:

new open and right click

**Comment by HangYang** [comment]
Hi @bfred-it you are much better than me, So I think you wont need to create merge request anymore unless you want to discuss with me something. You can take full control to this.
And I'm sorry I'd like to add you as secondary publisher to this extension, but my account is holding several extensions for my clients. So I can not add you to my account.
But I will take your idea, enable auto publish for this extension.
Thank you very much again, you make this extension much better and I learned a lot from you.

**Comment by bfred-it** [comment]
Ok :) 

I've been sending PRs for big features that you might not be interested in. But thank you for your trust!

I'll add the auto-publish feature later and after that you can go on Travis and enter the three values you can get from here: https://github.com/DrewML/chrome-webstore-upload/blob/master/How%20to%20generate%20Google%20API%20keys.md

**Comment by HangYang** [comment]
OK

**Pull request merged**
